# Official docker img.
image: docker:latest

services:
  # dind > Docker in Docker
  - docker:dind

before_script:
  - docker login -u ${dh_user} -p ${dh_pass}

variables:
  docker_img: "pipech/erpnext-docker-debian"

stages:
  - build

build-mas-py2:
  stage: build
  variables:
    docker_img_tag: "mas-py2-latest"
    python_version: "python"
    app_branch: "master"
    docker_img_wsql_tag: ${docker_img_tag}-w.sql
    docker_container_name: ${docker_img_tag}-con
  script:
    - docker build -t ${docker_img}:${docker_img_tag}
      --no-cache
      --build-arg pythonVersion=${python_version}
      --build-arg appBranch=${app_branch}
      .
    - docker push ${docker_img}:${docker_img_tag}
    - docker build -t ${docker_img}:${docker_img_wsql_tag}
      --no-cache
      --build-arg base_img=${docker_img}:${docker_img_tag}
      with_sql/.
    - docker push ${docker_img}:${docker_img_wsql_tag}
    - python image-tag.py
      ${docker_container_name}
      ${docker_img}
      ${docker_img_tag}
      ${docker_img_wsql_tag}
