# Official docker image.
image: docker:latest

services:
  # dind > Docker in Docker
  - docker:dind

before_script:
  - docker login -u $dh_user -p $dh_pass

variables:
  docker_image: "pipech/erpnext-docker-debian"

stages:
  - build
  - build-with-sql

build-mas-py2:
  stage: build
  variables:
    docker_image_tag: "mas-py2-latest"
  script:
    - docker build -t $docker_image:$docker_image_tag
      --build-arg pythonVersion=python
      --build-arg appBranch=master
      .
    - docker push $docker_image:$docker_image_tag

build-mas-py2-with-sql:
  stage: build-with-sql
  variables:
    docker_image_tag: "mas-py2-w.sql-latest"
  script:
    - docker build -t $docker_image:$docker_image_tag
      --build-arg base_image=$docker_image:mas-py2-latest
      trial_setup/.
    - docker push $docker_image:$docker_image_tag
