# Official docker img.
image: docker:latest

services:
  # dind > Docker in Docker
  - docker:dind

before_script:
  - docker login -u ${dh_user} -p ${dh_pass}

variables:
  docker_img: "pipech/erpnext-docker-debian"

stages:
  - build

build-mas-py2:
  stage: build
  variables:
    docker_img_tag: "mas-py2-latest"
    python_version: "python"
    app_branch: "master"
    docker_img_wsql_tag: ${docker_img_tag}-w.sql
    docker_container_name: ${docker_img_tag}-con
  script:
    - cat /etc/*-release

