language: python
env:
  global:
  - docker_img="pipech/erpnext-docker-debian"
  matrix:
  - python_version=python app_branch=master
  - python_version=python3 app_branch=staging
services:
- docker
script:
- echo "${docker_img}"
- echo [testtest]
- echo "${testtest}"
- echo "$[testtest]"
- echo "%[testtest]"
- echo "[testtest]"
- echo ${testtest}
- echo $[testtest]
- echo %[testtest]
- echo "[testtest]"
- echo "hello"
- echo "${python_version}"
- echo "${app_branch}"
