version: '3.3'
services:

services:
  reverse-proxy:
    image: traefik
    command: --api --docker # Enables the web UI and tells Træfik to listen to docker
    ports:
      - "80:80"     # The HTTP port
      - "8080:8080" # The Web UI (enabled by --api)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  mariadb:
    image: mariadb:10.2.12
    deploy:
      replicas: 1
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=123
    configs:
      - source: mariadb-conf
        target: /etc/mysql/conf.d/mariadb.cnf
      - source: mariadb-init-conf
        target: /home/init.sql
    volumes:
      - mariadb-data-volumes:/var/lib/mysql
    ports:
      - "3307:3306"

  redis-cache:
    image: redis:alpine
    deploy:
      replicas: 1
    configs:
      - source: redis-cache-conf
        target: /etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  redis-queue:
    image: redis:alpine
    deploy:
      replicas: 1
    configs:
      - source: redis-queue-conf
        target: /etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  redis-socketio:
    image: redis:alpine
    deploy:
      replicas: 1
    configs:
      - source: redis-socketio-conf
        target: /etc/conf.d/redis.conf
    command: ["redis-server","/etc/conf.d/redis.conf"]

  frappe:
    image: pipech/test:03
    deploy:
      replicas: 1
    ports:
      - "8000:8000"   #webserver_port
      - "9000:9000"   #socketio_port
      - "6787:6787"   #file_watcher_port
    volumes:
      - frappe-sites-volumes:/home/frappe/bench/sites
      - frappe-logs-volumes:/home/frappe/bench/logs
    stdin_open: true
    tty: true
    env_file:
      - ./env/frappe_app.env
    command: ["/home/frappe/production_config/entrypoint.sh"]
    labels:
      - "traefik.frontend.rule=Host:t01.spacecode.co.th, t02.spacecode.co.th"
      - "traefik.port=80"

volumes:
  frappe-sites-volumes:
  frappe-logs-volumes:
  mariadb-data-volumes:

configs:
  mariadb-conf:
    file: ./conf/mariadb-conf/mariadb.cnf
  mariadb-init-conf:
    file: ./conf/mariadb-conf/init.sql
  redis-cache-conf:
    file: ./conf/redis-conf/redis_cache.conf
  redis-queue-conf:
    file: ./conf/redis-conf/redis_queue.conf
  redis-socketio-conf:
    file: ./conf/redis-conf/redis_socketio.conf
