logLevel = "DEBUG"

defaultEntryPoints = ["https","http"]

[docker]
endpoint = "unix:///var/run/docker.sock"
exposedByDefault = false

[api]
dashboard = true
debug = true

[entryPoints]
    [entryPoints.http]
    address = ":80"
        [entryPoints.http.redirect]
        entryPoint = "https"
    [entryPoints.https]
    address = ":443"
        [entryPoints.https.tls]
